### ISSUE TITLE
Deepslice update

### ISSUE THREAD

**Issue by lukasvandenheuvel** [BIOP/ijp-imagetoatlas#99] opened 2021-09-21 17:13 UTC
Hi Nico,

Deepslice seems to have updated their webpage and the format of the results.xml file.
As a result, ABBA can no longer read the results file, and raises the error "could not parse results.xml" (see screenshot below).

![index](https://user-images.githubusercontent.com/55539564/134216210-e7e822fe-82d3-400a-bae3-178fa0831f15.jpg)

I think ABBA might need to be updated accordingly?

Thanks in advance!
Lukas

**Comment by PolarBean** [comment] 2021-09-22 04:31
@NicoKiaru 
This update was only pushed last night so unrelated to #97

I didn't think the update would effect ABBA, but for future updates we will give you notice to any changes to the XML. 

The main changes we have made are adding 'aligner' metadata to the XML so we can keep track of which version of DeepSlice was used if XMLs popup in data repositories, and looking now I think I may have broken the "first" and "last" XML values. Furthermore we've changed "height" and "width" to a negative value so its more clear that this is a placeholder. I might just change this to None though to be more clear. I'll fix the first and last issue promptly but please let me know if anything ive described here might be impacting ABBA.

**Comment by NicoKiaru** [comment] 2021-09-26 14:36
@lukasvandenheuvel do you still have this xml file ? I can't reproduce the issue, also what did you check in deepslice ?

**Comment by NicoKiaru** [comment] 2021-09-26 16:23
@PolarBean maybe I didn't check when there was an issue if there's been one. I checked again today with one slice and several slices, fixed the bug #97 which was indeed unrelated, and everything seems to work.

So no worry. I close the issue for now and @lukasvandenheuvel, if this fails again reopen the issue and post the xml file.

**Closed by NicoKiaru** 2021-09-26 16:23 UTC
