### ISSUE TITLE
Imported slices are extremely oversized in ABBA

### ISSUE THREAD

**Issue by maximilianweinhold** [BIOP/ijp-imagetoatlas#145] opened 2022-10-14 16:50 UTC
![importing_issue](https://user-images.githubusercontent.com/95586072/195899714-b6677eb8-f009-438d-8682-f3c2637b4919.PNG)

When importing slices from QuPath, the resulting images are massively oversized compared to the Allen Brain Atlas slices, and I can't find any way to resize the images. The QuPath images are ~6000 um x 4000 um, which appears to be the correct scale, so the issue appears to be with importing the images to ABBA. Please advise.

**Comment by NicoKiaru** [comment] 2022-10-15 08:12
> The QuPath images are ~6000 um x 4000 um

Just to be sure : is the pixel  size set automatically detected in QuPath ? Do you set it ? Do you set it BEFORE importing them in ABBA ? 

Can you screenshot and post the QuPath image tab of one of your image in QuPath ?

**Comment by maximilianweinhold** [comment] 2022-10-18 15:44
The images did not have scale metadata, so I manually set the pixel size. I did this before importing them in ABBA. 

Here's the QuPath image tab for one of the images: 
![image_tab](https://user-images.githubusercontent.com/95586072/196478823-f8c66646-66d6-465f-96f6-e2a341ca52fe.PNG)

**Comment by NicoKiaru** [comment] 2022-10-20 08:29
I'll try to look at this issue today, thanks for reporting. I may have broken something.

If I can't reproduce the issue, can you share one sample image ?

Thanks

**Comment by NicoKiaru** [comment] 2022-10-20 11:20
Ok, I can reproduce the issue with my images. I broke something indeed. I'll fix that asap

**Comment by NicoKiaru** [comment] 2022-10-20 12:42
@MrImaging makes sense, thanks for the feedback. it's actually the mistake I made when I thought I could reproduce the issue.

@maximilianweinhold can you check maybe if it's the same issue ? Can you save the QuPath project (maybe close it), re-open it and check that the pixel size was saved ?
When that's the case, re-import (not open state) in ABBA and tell us if the images are of the correct size.

**Comment by maximilianweinhold** [comment] 2022-10-20 18:47
@NicoKiaru It seems to be a different issue. Closing the QuPath Project and reopening it retains the pixel size, but the images in ABBA are still large.

**Comment by NicoKiaru** [comment] 2022-10-31 13:18
@maximilianweinhold I think we need to plan a zoom meeting to fix this.

Can you contact me by email (https://www.epfl.ch/research/facilities/ptbiop/staff/) to plan a zoom session ?

**Comment by NicoKiaru** [comment] 2023-03-01 16:47
> @NicoKiaru It seems to be a different issue. Closing the QuPath Project and reopening it retains the pixel size, but the images in ABBA are still large.

You need to re-import the QuPath project, and not open an existing state. This should fix the issue

**Comment by NicoKiaru** [comment] 2023-03-15 17:12
This issue should be fixed in the new ABBA release (v0.5+), planned for the end of the week

**Closed by NicoKiaru** 2023-03-15 17:12 UTC
